// Central place for the knobs we tune. Keeping them here means we don't have
// magic numbers scattered across the code, and it's easy to talk about each
// trade-off during the viva.

const path = require('path');

module.exports = {
  port: process.env.PORT || 3000,

  // Where the dataset lives. Generated by scripts/generate-dataset.js
  dataFile: path.join(__dirname, '..', 'data', 'queries.csv'),

  // How many suggestions we return for a prefix.
  suggestionLimit: 10,

  // ---- Distributed cache ----
  cache: {
    nodeCount: 4,        // number of logical cache nodes (think: 4 Redis shards)
    virtualNodes: 150,   // replicas per node on the hash ring -> smoother spread
    ttlMs: 30 * 1000,    // suggestions are cached for 30s before they expire
    maxEntriesPerNode: 5000, // simple LRU bound so memory doesn't grow forever
  },

  // ---- Batch writes ----
  batch: {
    maxSize: 50,          // flush once this many submissions are buffered
    flushIntervalMs: 2000, // ...or every 2s, whichever comes first
  },

  // ---- Trending / recency ----
  // We keep a "recent score" per query that decays over time. Half-life is how
  // long it takes for a burst of searches to lose half its weight.
  trending: {
    halfLifeMs: 5 * 60 * 1000, // 5 minutes
    // How strongly recency competes with (log-dampened) popularity in enhanced
    // mode. Log10 popularity sits in ~0..6, so with a weight of 3 even a couple
    // of recent searches can lift a query above the all-time leaders -- while
    // the decay still pulls it back down afterwards.
    recencyWeight: 3,
  },
};
